stages:
  - build
  - deploy

build:
    stage: build
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker build --pull -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE

# deploy-prod:
#     stage: deploy
#     before_script:
#         - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     script:
#         - docker pull $CI_REGISTRY_IMAGE
#         - docker stop $CI_PROJECT_NAME || true && docker rm $CI_PROJECT_NAME || true
#         - docker run --restart=unless-stopped -d -itd --name=$CI_PROJECT_NAME -p 127.0.0.1:50408:3000 $CI_REGISTRY_IMAGE
#     tags:
#         - ru
